### ISSUE TITLE
bison & getconf missing for kernel build or broken PATH

### ISSUE THREAD

**Issue by PeterHuewe** [landley/mkroot#2]
Hi,
when I try to cross compile a kernel using
`CROSS_COMPILE=arm-bcm2708-linux-gnueabi- ./mkroot.sh -n TARGET="armv7l" kernel`
I get the following error message:
```
linux-4.16/virt/lib/irqbypass.c
make: getconf: Command not found
make: getconf: Command not found
make: getconf: Command not found
  YACC    scripts/kconfig/zconf.tab.c
/bin/sh: bison: command not found
make[1]: *** [scripts/Makefile.lib:217: scripts/kconfig/zconf.tab.c] Error 127
```

The PATH within the modules/kernel is set to:
`/fast/tools/arm-bcm2708/arm-bcm2708-linux-gnueabi/bin:/fast/mkroot/airlock`
my regular PATH is
`/fast/tools/arm-bcm2708/arm-bcm2708-linux-gnueabi/bin/:/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0:/usr/x86_64-pc-linux-gnu/powerpc-unknown-linux-gnu/gcc-bin/4.7.2:/usr/lib/llvm/5/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/games/bin`

The missing bison and getconf are located under /usr/bin
Is there any reason why /usr/bin gets striped out somehow?

**Comment by landley** [comment]
Yeah, sorry: I added them to toybox's "make install_airlock" but haven't updated
the release number in mkroot yet. I plan to cut a release this weekend, but am
poking at adding an m68k target first.

In the meantime:

  rm -rf airlock
  ./cross.sh x86_64 ./mkroot.sh HOST_EXTRA='bison flex'

**Comment by TheDevMinerTV** [comment]
Thanks Rob!
I actually looked into this and wanted to post the same answer. . .
